"""empty message

Revision ID: 43924d853130
Revises: 0db43aa6595a
Create Date: 2024-04-24 18:47:48.440191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43924d853130'
down_revision = '0db43aa6595a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personajes',
    sa.Column('id_personaje', sa.Integer(), nullable=False),
    sa.Column('name_personaje', sa.String(length=120), nullable=False),
    sa.Column('age_personaje', sa.String(length=80), nullable=False),
    sa.Column('weapon_personaje', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_personaje'),
    sa.UniqueConstraint('name_personaje')
    )
    op.drop_table('personajes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='personajes_pkey'),
    sa.UniqueConstraint('email', name='personajes_email_key')
    )
    op.drop_table('Personajes')
    # ### end Alembic commands ###
