"""empty message

Revision ID: 4e6133be68f1
Revises: 
Create Date: 2024-05-03 18:26:15.824248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6133be68f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personajes',
    sa.Column('id_personajes', sa.Integer(), nullable=False),
    sa.Column('name_personajes', sa.String(length=120), nullable=False),
    sa.Column('age_personajes', sa.String(length=80), nullable=False),
    sa.Column('weapon_personajes', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_personajes'),
    sa.UniqueConstraint('name_personajes')
    )
    op.create_table('Planetas',
    sa.Column('id_planeta', sa.Integer(), nullable=False),
    sa.Column('name_planeta', sa.String(length=120), nullable=False),
    sa.Column('galaxia_planeta', sa.String(length=80), nullable=False),
    sa.Column('size_planeta', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_planeta'),
    sa.UniqueConstraint('name_planeta')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_personajes', sa.Integer(), nullable=True),
    sa.Column('id_planeta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personajes'], ['Personajes.id_personajes'], ),
    sa.ForeignKeyConstraint(['id_planeta'], ['Planetas.id_planeta'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Favoritos')
    op.drop_table('user')
    op.drop_table('Planetas')
    op.drop_table('Personajes')
    # ### end Alembic commands ###
